### ISSUE TITLE
"An item with the same key has already been added" dialog popup after the second console window and before the report is shown

### ISSUE THREAD

**Issue by StingyJack** [the-dext/RunCoverletReport#10]
The title of the dialog box is the default "Microsoft Visual Studio" and the message is the quoted value from the issue title. 

Are there any options I can set to capture the console output or whatever else may be contributing to create this error?

**Comment by StingyJack** [comment]
I have narrowed this down to being caused by the use of linked files (where one project refers files from another project as links).  I'm not sure what repo that belongs to (coverlet, here, somewhere else). If I knew what popped the error dialog that would help clue me in. @the-dext - any advice on which repo or how to figure that out?

**Comment by StingyJack** [comment]
Nvm.. I see where the problem is. PR incoming

**Comment by the-dext** [comment]
released.
