### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SergejFomin** [the-dext/RunCoverletReport#12]
Would it be possible to add an open-source license to this repository? 
I really like the extension and the help it provides, but unfortunately, it seems as if the work on the projects has stopped. 
Without a license, I would not be able to make any modifications to the project for my use case.
Thank you in advance.

**Comment by the-dext** [comment]
Glad you like it, and apologies for not building upon it some more. I've just found it very hard to find the time, and the documentation for the VS Extensions SDK seems quite hard to figure out sometimes.

No problem with having a license though - I've just committed one. You're free to make changes. Hope it continues to work for you.
