### ISSUE TITLE
Doesn't work with Docker Compose Project in solution (*.dcproj)

### ISSUE THREAD

**Issue by woodworm83** [the-dext/RunCoverletReport#4]
When a solution contains a Docker Compose Project (*.dcproj) the plugin fails to execute the tests.

**Comment by woodworm83** [comment]
Seems to be a problem of dotnet restore command. But adding "--no-restore" option solves the issue.

**Comment by the-dext** [comment]
Closing this as your fix has accepted. Thank you very much for contributing.
