### ISSUE TITLE
Highlighting disappears on scrolling

### ISSUE THREAD

**Issue by R0Wi** [the-dext/RunCoverletReport#8]
I'm using VS2019 16.8.4. If i run a new coverage report and toggle the "Tools -> Toggle Code Coverage Highlighting" the coverage is shown in the VS texteditor. But when i scroll down and back up the highlighting disappears.

https://user-images.githubusercontent.com/19730957/111605617-bbe48980-87d6-11eb-90d6-ccca31f5b231.mp4

Do you have any idea what might be wrong? Please let me know if i can help somehow.

**Comment by the-dext** [comment]
Hmm.
I'm a bit baffled why it hasn't worked for you. The code tells visual studio to apply an an adornment and visual studio should look after it from then on, as far as I know.
I just pulled MediatR from github and tried out out on that and it worked fine for me.
It's a bit of a long shot but have you tried switching between hardware and software rendering in the visual studio options ?

I used to have issues a bit like what you are seeing when I was using remote desktop onto my old developmenr machines, and using Resharper on it. Are you working locally?


https://user-images.githubusercontent.com/8195526/111825164-0b15e180-88df-11eb-8147-7b4a4de4f4ff.mp4

**Comment by R0Wi** [comment]
Thanks for your answer. Indeed i'm working via RDP and Resharper is also installed. Do you think this could be related? And could you tell me how to switch rendering? Thanks in advance.

**Comment by the-dext** [comment]
I’m not sure but I think software rendering is always used by visual studio when using RDP. The setting for it is in the Visual studio preferences. 

I don’t have a way to try out RDP but I will try local software rendering when I can. Not sure what to do if I can recreate it, but it’ll be a start.

**Comment by the-dext** [comment]
Just tried it with visual studio software rendering enabled and didn't have any problems with that either, so not sure what I can do to help.

**Comment by R0Wi** [comment]
Thanks for your feedback. I'll try some VS settings. Maybe we can leave this open for the meantime?

**Comment by the-dext** [comment]
> Thanks for your feedback. I'll try some VS settings. Maybe we can leave this open for the meantime?

Sure
